"use client";

import { useState } from "react";
import { api } from "@/lib/api";

type Module = "replacement" | "vfd" | "power_quality";

interface Props {
  module: Module;
  result: unknown;
}

const MODULE_LABEL: Record<Module, string> = {
  replacement: "Motor Replacement",
  vfd: "VFD Savings",
  power_quality: "Power Quality",
};

export default function AIInsights({ module, result }: Props) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [text, setText] = useState("");
  const [model, setModel] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  const handleRequest = async () => {
    setState("loading");
    setText("");
    setErrorMsg("");
    try {
      const res = await api.ai.insights(module, result);
      setText(res.insights);
      setModel(res.model);
      setState("done");
    } catch (e) {
      const msg = (e as Error).message;
      setErrorMsg(
        msg.includes("GEMINI_API_KEY")
          ? "Gemini API key not configured. Set GEMINI_API_KEY in backend/.env and restart the server."
          : msg
      );
      setState("error");
    }
  };

  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 bg-slate-50 border-b border-slate-200">
        <div>
          <span className="text-sm font-semibold text-slate-700">AI Engineering Insights</span>
          <span className="ml-2 text-xs text-slate-400">Gemini interprets your {MODULE_LABEL[module]} results</span>
        </div>
        {state !== "loading" && (
          <button
            onClick={handleRequest}
            className="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-600 transition-colors"
          >
            {state === "done" ? "Regenerate" : "Get AI Insights"}
          </button>
        )}
        {state === "loading" && (
          <span className="text-xs text-slate-400 animate-pulse">Analysing with {model || "Gemini"}...</span>
        )}
      </div>

      {state === "idle" && (
        <div className="px-4 py-6 text-center text-sm text-slate-400">
          Click "Get AI Insights" to have Gemini interpret these results in engineering context.
        </div>
      )}

      {state === "loading" && (
        <div className="px-4 py-6 space-y-2">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="h-3 bg-slate-100 rounded animate-pulse"
              style={{ width: `${90 - i * 8}%` }}
            />
          ))}
        </div>
      )}

      {state === "error" && (
        <div className="px-4 py-4 text-sm text-red-600 bg-red-50">
          {errorMsg}
        </div>
      )}

      {state === "done" && text && (
        <div className="px-4 py-4">
          <div className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{text}</div>
          <div className="mt-3 pt-3 border-t border-slate-100 text-xs text-slate-400">
            Generated by {model}. AI output is for engineering reference only — verify before acting on recommendations.
          </div>
        </div>
      )}
    </div>
  );
}
